const countries = [
  {
    id: 1,
    name: "Germany",
    population: "81,770,900",
    region: "Europe",
    capital: "Berlin",
    language: "German/English",
    img: "./images/Germany.png",
  },
  {
    id: 2,
    name: "United States of America",
    population: "323,947,000",
    region: "Americas",
    capital: "Washington, D.C.",
    language: "English",
    img: "./images/USA.png",
  },
  {
    id: 3,
    name: "Brasil",
    population: "206,135,893",
    region: "Americas",
    capital: "Brasilia",
    language: "Brasil/Hunsrik",
    img: "./images/Brazil.png",
  },
  {
    id: 4,
    name: "Iceland",
    population: "334,300",
    region: "Europe",
    capital: "Reykjavík",
    language: "Scandinavian",
    img: "./images/Iceland.png",
  },
  {
    id: 5,
    name: "Afghanistan",
    population: "27,657,145",
    region: "Asia",
    capital: "Kabul",
    language: "Farsi",
    img: "./images/Afganistan.png"
  },
  {
    id: 6,
    name: "Aland Islands",
    population: "28,875",
    region: "Europe",
    capital: "Mariehamn",
    language: "Swedish",
    img: "./images/Icelands.png"
  },
  {
    id: 7,
    name: "Albania",
    population: "2,886,026",
    region: "Europe",
    capital: "Tirania",
    language: "Albanian",
    img: "./images/Albania.png"
  },
  {
    id: 8,
    name: "Algeria",
    population: "40,400,000",
    region: "Africa",
    capital: "Algiers",
    language: "Afrosiatic",
    img: "./images/Algeria.png",
  },
];